/* Generated by Vercel build. Public key only; never place service_role/secret here. */
window.SMART_QC_CONFIG = {
  "supabase": {
    "url": "",
    "key": "",
    "workspace": "smartqc-qyh-shared"
  }
};
