import { writeFileSync, readFileSync } from 'node:fs';

const url = (process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL || '').trim().replace(/\/$/, '');
const key = (process.env.SUPABASE_PUBLISHABLE_KEY || process.env.VITE_SUPABASE_PUBLISHABLE_KEY || '').trim();
const workspace = (process.env.SMART_QC_WORKSPACE || 'smartqc-qyh-shared').trim() || 'smartqc-qyh-shared';

const config = `/* Generated by Vercel build. Public key only; never place service_role/secret here. */\nwindow.SMART_QC_CONFIG = ${JSON.stringify({ supabase: { url, key, workspace } }, null, 2)};\n`;
writeFileSync('config.js', config, 'utf8');

if (!url || !key) {
  console.warn('SMART QC: Supabase environment variables are not set. The app will still run, but cloud sync must be configured from Hệ thống → Dữ liệu.');
} else {
  console.log('SMART QC: Supabase public configuration injected for workspace:', workspace);
}
